### ISSUE TITLE
Website is down ?

### ISSUE THREAD

**Issue by jsmadja** [poliva/ggpo#4]
What's wrong with https://www.fightcade.com/ ?

**Comment by poliva** [comment]
there was an issue with the server, it has been resolved now. Website is up & running.

**Comment by machodelmsz** [comment]
Hi poliva!....Need help!!!....I can´t loggin to FightCade....it could be that Fightcade erase my account?...please I NEED FIGHTCADE!!!....help!!!.... thanks!!!...
